version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env
    command: sh -c "pnpm db:deploy && pnpm start"
    ports:
      - $PORT:$PORT
